---
title: "22-11-2024"
author: "maulid_japhary"
date: "2024-11-22"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

#importing data saved as rds (r file format)

object_name <- readRDS("path/to/file_name.rds")
```{r}
here::here("data","human_data_selection_dedup.rds")
human_selection <- readRDS(here::here("data","human_data_selection_dedup.rds"))
```
```{r}
#install.packages("RSQLite")
library(RSQLite)
library(tidyverse)
library(here)
```

```{r}
sqlite_path <- "c:/WHONET/data/TZA-INIKA_TZ-2024.sqlite"
sqlite_path
dbconn <- DBI::dbConnect(RSQLite::SQLite(), sqlite_path)
```
```{r}
dbconn
```
```{r}
dbListTables(dbconn)
```

<!--
```{r}
DBI::dbDisconnect(dbconn)

```
-->

```{r}
mytada_recipie <- tbl(dbconn,"isolates")
str(mytada_recipie)
head(mytada_recipie)
```

```{r}
show_query(mytada_recipie)
```

```{r}
mydata <- mytada_recipie %>% collect()
```

```{r}
mydata %>%
  dplyr::inner_join(human_selection %>% select(1:3),
                    by = c("PATIENT_ID"= "INIKA_OH_TZ_ID")) %>%
  head() %>%
  view()
```

